### ISSUE TITLE
add support for importing multiple saved queries by json

### ISSUE THREAD

**Issue by geransmith** [Axonius/axonius_api_client#124]
The current "axonshell devices saved-query add-from-json" command only accepts a single JSON formatted saved query.

To allow for bulk export / import of saved queries, we should add the ability to import the JSON dump that is created via the "axonshell devices get -xf json" command.

**Comment by lifehackjim** [comment]
solved by https://github.com/Axonius/axonius_api_client/commit/77e9eeaf35b11fb05f7c680661b2a76335498889
