### ISSUE TITLE
Update wording in meta/about regarding supported API client version

### ISSUE THREAD

**Issue by Phillips-Chris** [Axonius/axonius_api_client#128]
Currently the meta/about displays:
{
  "Build Date": "Tue Jul 7 21:58:13 UTC 2020",
  "Customer ID": "dd70ad9ef5ff46108fb218c4d401fcda",
  "Installed Version": "",
  "api_client_version": "3.1.4"
}

The last line could be more descriptive that it is showing the supported/required API client version needed. Something along the lines of "required_api_client_version": "3.1.4".

**Comment by lifehackjim** [comment]
not fixing for now, awaiting REST API server re-vamp
