### ISSUE TITLE
Allow multiple field name types when using --field-exclude

### ISSUE THREAD

**Issue by geransmith** [Axonius/axonius_api_client#138]
At this time the following formats can be used with the --field-exclude flag; "name", "qualified name", "base name", or "column title". 

To help make the field exclusion easier to managed, we should allow the same select options that we have when using the "--field" option.

**Comment by lifehackjim** [comment]
Thanks, I will attempt to get this done by 11/1/2020

**Comment by lifehackjim** [comment]
done in 4.1.0
