### ISSUE TITLE
API Library: don't error out on bad field names

### ISSUE THREAD

**Issue by geransmith** [Axonius/axonius_api_client#153]
Currently, if you specify a field that does not exist on an asset to be added to your script, the library will respond with a list of available fields. This behavior is great in axonshell but not as helpful when using the API Library.

I suggest adding a flag that allows for not returning usable fields and to create the specified field and populate all values with null. For programmatic support, it would be better to return the field with a null value, so the query completes and returns what it does have rather than failing with no results.

**Comment by lifehackjim** [comment]
Source: Ticket 5141

**Comment by lifehackjim** [comment]
Ignoring invalid fields is easy enough, but adding null values for fields that are unexpected / not in the schemas for the fields is much more difficult.
