### ISSUE TITLE
Set system users source via API

### ISSUE THREAD

**Issue by progmatic73** [Axonius/axonius_api_client#191]
Currently we can call api/settings/users and get source of the user but we are not able to post/put the users source.

**Comment by progmatic73** [comment]
Hi @lifehackjim 

A little background so you know why I was inquiring about it.

Currently we have SSO login or user/pwd login method.  If a user clicks SSO for the first time, we have to create a csv(username,saml), then run (docker container) a py script that was given to us. The script appears to connect to a mongo collection to change the source.  

Wanted to simplify as it's all too confusing to me.  😕    Thanks for you response!

**Comment by lifehackjim** [comment]
@progmatic73 please open a ticket by sending an email to support@axonius.com so we can help supply further details
