### ISSUE TITLE
Weighting concept

### ISSUE THREAD

**Issue by frank-bailey** [Axonius/axonius_api_client#48]
- for a general field, say hostname
- get the values of hostname from ALL adapters in system
- allow weighting on a 1-10 score
- if adapter x with a score of 10 has hostname1, add that as a value for a key
  weighted_hostname
- if adapter x with a score of 10 has NO hostname, fallback to adapter y with a score
  of 7

Concept:

```text
--field-weight hostname:aws=10,sccm=10,solwarinds=10,jamf=9,ad=9,bluecat=1

# (score aws as the heaviest)
weighted.hostname
```

**Comment by lifehackjim** [comment]
this has been solved by the preferred_ fields
